title = "@ahmubashshir's blog"
paginate = 6

baseURL = 'https://ahmubashshir.github.io'
theme = 'github.com/adityatelange/hugo-PaperMod'
enableInlineShortcodes = true
enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false
enableEmoji = true
enableGitInfo = true
defaultContentLanguage = 'bn'

[languages.bn]
weight = 1
LanguageName = ':bangladesh:'

[languages.en]
weight = 2
LanguageName = ':us:'

[minify]
disableXML = false
minifyOutput = true

[outputs]
home = ["HTML", "RSS", "JSON"]
section = ['HTML', 'RSS']

[outputFormats.RSS]
mediatype = 'application/rss+xml'
baseName = 'rss'

[taxonomies]
category = 'categories'
tag = 'tags'
series = 'series'

[privacy.vimeo]
disabled = false
simple = true
[privacy.twitter]
disabled = false
enableDNT = true
simple = true
[privacy.instagram]
disabled = false
simple = true
[privacy.youtube]
disabled = false
privacyEnhanced = true

[services.instagram]
disableInlineCSS = true
[services.twitter]
disableInlineCSS = true
