[highlight]
anchorLineNos = false
codeFences = true
guessSyntax = true
lineNos = false
# lineNoStart = 1
# lineNumbersInTable = true
noClasses = false
style = 'dracula'
tabWidth = 4

[goldmark.renderer]
unsafe = true

[tableOfContents]
endLevel = 3
ordered = true
startLevel = 2
