env = 'production'
description = 'Evidence of my terrible writing skills.'
keywords = [
	'blog', 'linux',
	'ahmubashshir',
	'technology',
	'nature photography'
]
author = "Mubashshir"
defaultTheme = 'dark'

disableThemeToggle = false
ShowFullTextinRSS = true
ShowReadingTime = true
ShowShareButtons = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
disableSpecial1stPost = true
disableScrollToTop = false
comments = true
hidemeta = false
hideSummary = false
showtoc = true
tocopen = false
images = ['/assets/cover/home.png']

[label]
text = "‍"
icon = "/assets/image/favicon-32x32.png"
iconHeight = 32

[homeInfoParams]
Title = "Ahmad Hasan Mubashshir"
Content = "Student, bookworm, Linux Enthusiast, Otaku ;)"

[analytics.google]
SiteVerificationTag = "1AayfMJ_TLCrPwoK12kv_LhdWrH1tARYKK6oHPBjOh0"

[[socialIcons]]
name = 'GitHub'
url = 'https://github.com/ahmubashshir'
[[socialIcons]]
name = 'StackOverflow'
url = 'https://stackoverflow.com/users/9123082'

[[socialIcons]]
name = 'Telegram'
url = 'https://t.me/ahmubashshir'

[[socialIcons]]
name = 'Reddit'
url = 'https://reddit.com/u/ahmubashshir'

[[socialIcons]]
name = 'Twitter'
url = 'https://twitter.com/ahmubashshir'

[[socialIcons]]
name = 'Email'
url = 'mailto:ahmubashshir@gmail.com'

[[socialIcons]]
name = 'RSS'
url = 'index.xml'

[[socialIcons]]
name = 'Quotes'
url = 'quotes'

[editPost]
URL = "https://github.com/ahmubashshir/ahmubashshir.github.io/tree/master/content/posts"
Text = "Suggest Changes" # edit text
appendFilePath = true # to append file path to Edit link

[cover]
hidden = true # hide everywhere but not in structured data
hiddenInList = true # hide on list pages and home
hiddenInSingle = true # hide on single page
relative = false

[assets]
disableFingerprinting = true
favicon = "/assets/image/favicon.ico"
favicon16x16 = "/assets/image/favicon-16x16.png"
favicon32x32 = "/assets/image/favicon-32x32.png"
apple_touch_icon = "/assets/image/apple-touch-icon.png"
safari_pinned_tab = "/assets/image/safari-pinned-tab.svg"
msTileColor = "#1d1e20"
vtag = '8jl4JnrGke'

[pwa]
color = "#dadadb"
bgColor = "#1d1e20"
display = 'standalone'
orientation = 'portrait-primary'

[fuseOpts]
isCaseSensitive = false
shouldSort = true
location = 0
distance = 1000
threshold = 0.4
minMatchCharLength = 0
keys = ["title", "permalink", "summary", "content"]
