# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "@ahmubashshir's blog"
email: ahmubashshir@gmail.com
timezone: Asia/Dhaka
description: >- # this means to ignore newlines until "baseurl:"
  Evidence of my terrible writing skills.
baseurl: "" # the subpath of your site, e.g. /blog
url: https://ahmubashshir.github.io # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: ahmubashshir
github_username:  ahmubashshir
twitter:
  username: ahmubashshir
  card: summary
logo: /assets/image/apple-touch-icon-144x144-precomposed.png

webmaster_verifications:
  google: "1AayfMJ_TLCrPwoK12kv_LhdWrH1tARYKK6oHPBjOh0"

# Build settings
markdown: kramdown
remote_theme: "ahmubashshir/so-simple-theme@devel"
skin: "/assets/css/skins/dark.css"
paginate: 10  # amount of posts to show per page
paginate_path: "/:num"
permalink: /:collection/:year/:month/:day/:title
category_archive_path: "/categories/#"
tag_archive_path: "/tags/#"
search_full_content: false
mathjax:
  enable: false

plugins:
- jekyll-seo-tag
- jekyll-sitemap
- jekyll-feed
- jekyll-paginate
- jekyll-asciinema
- jekyll-target-blank
- jemoji

collections:
  posts:
    label: Posts
    output: true
  slides:
    label: Slides
    output: true

defaults:
  - scope:
      path: _posts
      type: posts
    values:
      layout: post
      comments: true
      share: true
  - scope:
      path: _slides
      type: slides
    values:
      layout: slide
      permalink: /slide/:year/:month/:day/:title

feed:
  path: atom.xml

utterances:
  repo: ahmubashshir/ahmubashshir.github.io
  term: pathname
  theme: photon-dark

liquid:
  error_mode: strict

author:
  name: Mubashshir
  picture: https://www.gravatar.com/avatar/0c741be6074cce563d08dd9bb07a8770
  email: ahm@disroot.org
  twitter: ahmubashshir
  links:
  - title: Mail
    url: mailto:ahmubashshir@gmail.com
    icon: fas fa-at
  - title: Reddit
    url: https://reddit.com/u/ahmubashshir
    icon: fab fa-reddit
  - title: Telegram
    url: https://t.me/ahmubashshir
    icon: fab fa-telegram

head_scripts:
- https://unpkg.com/jquery@3.3.1/dist/jquery.min.js
- https://use.fontawesome.com/releases/v5.0.12/js/all.js
- https://unpkg.com/ackee-tracker-consent/dist/ackee-tracker-consent.min.js

footer_scripts:
- /assets/js/main.min.js

footer_links:
- title: GitHub
  url: https://github.com/ahmubashshir
  icon: fab fa-github-square
- title: Feed
  url: atom.xml
  icon: fas fa-rss-square
- title: Quotes
  url: quotes
  icon: fas fa-quote-left
- title: Status
  url: https://stats.uptimerobot.com/gM3v9IlZMz
  icon: fas fa-server
misc:
  favicon-version: 8jl4JnrGke
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
- Gemfile
- Gemfile.lock
- package.json
- package-lock.json
- node_modules
- vendor
